Width: 2600             # 图像宽度
Height: 2160            # 图像高度
Offset_x: 0             # X方向偏置
Offset_y: 0             # Y方向偏置

FrameRateEnable: false  # 帧率使能 
FrameRate: 5            # 帧率

ExposureTime: 50000     # 曝光时间（单位：微秒）

GammaEnable: true       # 伽马校正启用开关
Gamma: 0.7              # 伽马因子

TriggerMode: 1          # 触发模式
TriggerSource: 0        # 触发源
