# 图像格式控制
Width:  2600            # 图像宽度
Height: 2160            # 图像高度
BinningHorizontal: 2    # 水平合并（only 1 2 4）要合并在一起的水平像素数，会降低分辨率提高亮度
BinningVertical:   2    # 垂直合并（only 1 2 4）

# 采集控制
AcquisitionFrameRate: 10.0         # 采集帧率（Fps）
AcquisitionFrameRateEnable: true   # 使能采集帧率控制
TriggerMode: 0          # 触发模式（0：关闭 1：打开）
TriggerSource: 0        # 触发源（0：线路0）
TriggerActivation: 0    # 触发极性（0：上升沿 1：下降沿）
ExposureTime: 40000     # 曝光时间（us）
ExposureAuto: 2         # 自动曝光（0：关闭 1：一次 2：连续）
AutoExposureTimeLowerLimit: 3     # 自动曝光时间下限（us）
AutoExposureTimeUpperLimit: 80000 # 自动曝光时间上限（us） 太高会影响帧率，图像模糊

# 模拟控制
BlackLevel: 100          # 模拟黑电平百分比
BlackLevelEnable: true  # 黑电平使能
BalanceWhiteAuto: 1     # 自动白平衡（0：关闭 1：连续 2：一次）
Gamma: 0.7              # 伽马校正
GammaEnable: true       # 伽马校正使能